// <auto-generated />
namespace Physiotech.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Virtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Virtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201312021425366_Virtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
