// <auto-generated />
namespace Physiotech.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Crap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Crap));
        
        string IMigrationMetadata.Id
        {
            get { return "201312020102296_Crap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
