// <auto-generated />
namespace Physiotech.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Code : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Code));
        
        string IMigrationMetadata.Id
        {
            get { return "201312020047408_Code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
