// <auto-generated />
namespace Physiotech.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Clinic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Clinic));
        
        string IMigrationMetadata.Id
        {
            get { return "201311150630185_Clinic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
